### ISSUE TITLE
Project is Broken "com.unity.entities": "0.0.12-preview.7" does not ever exists.

### ISSUE THREAD

**Issue by Lelegithub** [ciro-unity/Danmaku#1]
Project is Broken "com.unity.entities": "0.0.12-preview.7" does not ever exists.
tried both "0.0.12-preview.8" and "0.0.12-preview.6" but it crashes with all Maths and Collections library being not compatible.
It would be nice to have a working project with stable manifest packages.
Sent and notified also to Unity Learn community.

**Comment by ciro-unity** [comment]
Thanks Lele, the issue has been fixed by removing all references to ECS. It was never intended to be an ECS demo in any case.
